# Dynamixel XM430-W350
ADDR_PRO_OPERATING_MODE     = 11
ADDR_PRO_HW_ERR_STATES      = 70
ADDR_PRO_TORQUE_ENABLE      = 64
ADDR_PRO_GOAL_POSITION      = 116
ADDR_PRO_PRESENT_POSITION   = 132
ADDR_PRO_CURRENT_LIMIT      = 38
ADDR_PRO_GOAL_CURRENT       = 102
ADDR_PRO_PRESENT_CURRENT    = 126
                                
OP_CURRENT_CONTROL_MODE     = 0
OP_POSITION_CONTROL_MODE    = 3
TORQUE_ENABLE               = 1
TORQUE_DISABLE              = 0